### ISSUE TITLE
Unable to pull docker image Azureml Base Gpu openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04

### ISSUE THREAD

**Issue by clthorre** [Azure/MachineLearningNotebooks#1186]
Hello. When I run:
`docker pull mcr.microsoft.com/azureml/base-gpu:openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04`
I get an error message:
`Error response from daemon: manifest for mcr.microsoft.com/azureml/base-gpu:openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04 not found: manifest unknown: manifest tagged by "openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04" is not found` 

However this is listed as an image on docker hub here with 201 downloads. https://hub.docker.com/_/microsoft-azureml-openmpi3-1-2-cuda10-2-cudnn7-ubuntu18-04

I can also see the code for it in the azure/AzureMl-Containers repo here https://github.com/Azure/AzureML-Containers/blob/master/base/gpu/openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04/Dockerfile

I want this image as it has NCCL version 2.7.4 whereas the one with cuda 10.1 has NCCL 2.4.8 which has ring issues. https://github.com/NVIDIA/nccl/issues/262

Will the cuda 10.2 image be available soon?

**Comment by vizhur** [comment]
there is no such image, ie tag on base-gpu image.
please use  
>> docker pull `mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04`
Using default tag: latest
latest: Pulling from azureml/openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04
7595c8c21622: Downloading [=====>

**Comment by clthorre** [comment]
Hello vizhur, thank you for pointing me to the correct docker image!

**Comment by lostmygithubaccount** [comment]
@vizhur where is the Python environment for this image? and how would I find this out?

**Comment by vizhur** [comment]
sorry Cody, I didn't get your question. What is the python environment you are talking about?

**Comment by lostmygithubaccount** [comment]
I'm trying to use this image (or an image) in a dockerfile, running some additional pip commands on top: 

```python
dockerfile = """FROM mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04
RUN apt-get update && \
pip install --upgrade dask && \ 
pip install --upgrade distributed && \ 
pip install --upgrade bokeh && \ 
pip install --upgrade asyncssh
"""

env = Environment("dask-env")
env.docker.enabled = True
env.docker.base_image = None
env.docker.base_dockerfile = dockerfile 
env.python.user_managed_dependencies = True
```

I start a run on my compute target, SSH into the node, and can only find `/usr/bin/python` and `/usr/bin/python3`, neither of which have the pip packages I installed:

![image](https://user-images.githubusercontent.com/54814569/96339462-b6c5b780-1049-11eb-9cdf-c97e893c9f15.png)

So I need to set the `remote_python` path to the correct Python interpreter, how would I find that?

**Comment by vizhur** [comment]
AzureML base images are not intended to be used like that, unfortunately... we are planning to make some improvements there to extend the use cases but obviously no ETA ;)

With the conda installed its interpreter becomes a default python, I think. You can try to python -m pip install mydeps. I would not recommend that either because it will install into conda base environment that is bad by definition and you won't be able to install certain deps like AzureML SDK because of the recently added nonsense in the base conda env. So clear way would be to create a new conda environment, activate it and install dependencies there. You can set -p to set the path for the env and use it as interpreter path if you want

Is there any reason to go with user managed? you can have your deps in the python section of the environment? What is the goal for apt-update, btw? The image is just released and we update it regularly if needed

**Comment by clthorre** [comment]
Hi @vizhur can you help me understand the way the AzureML base images are indented to be used? 

My current dockerfile is like this:
`FROM mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04
RUN apt-get update
COPY requirements.txt /tmp/requirements.txt
RUN pip install torch torchvision
RUN pip install tensorboard && \
    pip install future==0.17.1
RUN pip install nltk && \
    python -m nltk.downloader -d /usr/share/nltk_data all
RUN pip install -r /tmp/requirements.txt`

In my experiments all of the things in installed later in the docker file are present when I run my code in AML. And even by checking the config it is now using cuda 10.2 which my previous docker image did not. It was similar only with an older azureml/openmpi cuda dockerfile in the first line.

Does this seem like a correct usage case?
