### ISSUE TITLE
ImportError: cannot import name 'ShortSeriesHandlingValues'

### ISSUE THREAD

**Issue by synapticrumble** [Azure/MachineLearningNotebooks#1250]
![image](https://user-images.githubusercontent.com/3012940/100425761-69c7fe80-3055-11eb-8017-71bd32ced0f2.png)

Above is the error, when running the github (Azure/mslearn-aml-labs) 09-Automated_ML.ipynb using standard 4 Core, 14 GB RAM compute instance.

**Comment by lostmygithubaccount** [comment]
@synapticrumble it looks like this is an issue in another repository?

**Comment by cartacioS** [comment]
Hi @synapticrumble. Thanks for reaching out with this issues.

We believe this may be caused by inconsistent packages in the environment, specifically a older version of azureml-automl-core as compared to azureml-automl-runtime. Could you please run the following pip freeze and share the output here?

```
! pip freeze | grep azureml
```

**Comment by cartacioS** [comment]
Hi @synapticrumble, is there any update on this item? Else I can go ahead and close it.
