### ISSUE TITLE
No such file or directory error when running pipeline

### ISSUE THREAD

**Issue by kelsey-emnett** [Azure/MachineLearningNotebooks#1280]
When running a script to run my Azure ML pipeline on an attached compute instance, the software is autosaving my notebook with .amltemp at the end of my notebook name. Therefore, by the time Azure ML starts to run my pipeline, it can no longer find my script in my files and it gives me the following error:

```python
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/batch/tasks/shared/LS_root/mounts/clusters/azure-ml-compute/code/Users/first.lastname/Development/driver_notebook_file_name.ipynb.amltemp'
```

This is the code that leads to the error:
```python
# Example pipeline step
step1 = PythonScriptStep(name='Data Cleaning',
                             script_name="data_clean_step1.py",
                             arguments=['--outputs', modeling_clean_data,  '--exp_outputs', exp_clean_data],
                             inputs=[input_data],
                             outputs=[modeling_clean_data, exp_clean_data],
                             source_directory=os.getcwd(),
                             compute_target=compute_target,
                             runconfig=run_config,
                             allow_reuse=True)

modeling_steps = [step2, step3, step4, step5, step6]
all_steps = StepSequence(steps=[step1, modeling_steps, step7])
pipeline = Pipeline(workspace=ws, steps=all_steps)
run = exp.submit(pipeline)
run.wait_for_completion(show_output=True)
```

Identical code causing this error previously worked and I have had this issue on two different Azure tenants after upgrading to the new version of Azure ML. I sometimes get the error and sometimes do not with the same code. If I run many times it sometimes works, but I hit the error probably 7 times to every time it actually runs my code without an error.

**Comment by swanderz** [comment]
if this worked for weeks, before breaking, I agree that it looks strange. @abe

@kelsey-emnett, can you try creating an `.amlignore` file in the `Development/` directory and inside of it put `*.amltemp`.  This should ignore all `.amltemp` files. So the steps won't go looking for them.

Also worth noting that is is best practice to isolate scripts needed for PythonScriptSteps into their own folders, and changing the `source_directory` param to reference said folder instead of `os.getcwd()` This way, the `PythonScriptStep`
 - will have no reason to look for the `.amltemp` file because there won't be on in the directory you've assigned, and
- you won't be uploading unnecessary to the remote compute (there's no reason a pipeline step needs the driver notebook anyway, right?

**Comment by kelsey-emnett** [comment]
The suggestion @swanderz gave above worked. Once I put each pipeline script into its own folder in my working directory and set those folders as the source_directory in my pipeline steps, everything worked just fine. Here is the fix that worked:

```python
step1 = PythonScriptStep(name='Data Cleaning',
                             script_name="data_clean_step1.py",
                             arguments=['--outputs', modeling_clean_data,  '--exp_outputs', exp_clean_data],
                             inputs=[input_data],
                             outputs=[modeling_clean_data, exp_clean_data],
                             # Line below is the line changed to correct issue after creating a folder for each script
                             source_directory=os.path.join(os.getcwd(),'data_cleaning'),
                             compute_target=compute_target,
                             runconfig=run_config,
                             allow_reuse=False)
```
