### ISSUE TITLE
AzureML SDK (dataprep) install on Databricks

### ISSUE THREAD

**Issue by kumaranpravin** [Azure/MachineLearningNotebooks#129]
I am trying to use the automl feature using the Databricks as the compute environment. 
So,if i try to use the dataprep package, i get "no module found" error. But i could able to import the other packages like azureml.core.

RunTime Version: 4.3

![image](https://user-images.githubusercontent.com/29369204/49788445-59cd8c00-fd64-11e8-82ab-6aef4decd38a.png)

_Originally posted by @kumaranpravin in https://github.com/Azure/MachineLearningNotebooks/issue_comments#issuecomment-446114803_

**Comment by rongduan-zhu** [comment]
Hi @kumaranpravin, which version of Automated ML do you have installed on your Databricks cluster?

**Comment by rongduan-zhu** [comment]
@kumaranpravin sorry, I somehow thought you were using [Automated ML](https://docs.microsoft.com/en-us/azure/machine-learning/service/tutorial-auto-train-models) on Databricks. 

Data Prep is currently not installed as part of `azureml-sdk`, you will need add `azureml-dataprep` to your cluster dependencies in order to use Data Prep.
![image](https://user-images.githubusercontent.com/5406634/49841656-39ee9600-fd6d-11e8-9970-0a17a765a225.png)
![image](https://user-images.githubusercontent.com/5406634/49841710-7de19b00-fd6d-11e8-87c4-376321634a0f.png)

**Comment by kumaranpravin** [comment]
Thanks, now i can access it.

**Comment by rodneyjoyce** [comment]
> Thanks, now i can access it.

Ah - I can see you can access it now - what was your experience with using Data Prep on Databricks? Does it add value and is it worth learning?
