### ISSUE TITLE
Tried to use on Azure Tutorial but file is corrupted or empty

### ISSUE THREAD

**Issue by residentx10** [Azure/MachineLearningNotebooks#1396]
https://docs.microsoft.com/en-us/azure/machine-learning/tutorial-automated-ml-forecast 

I downloaded bike.no.csv to my local computer and opened file but corrupted. I tried to pull it into Azure ML but file is useless. 
[bike-no.zip](https://github.com/Azure/MachineLearningNotebooks/files/6178806/bike-no.zip)

**Comment by kvijaykannan** [comment]
Thanks for reaching to us. We tried downloading this file, and it worked fine. The file is not corrupted after the download.

**Comment by CESARDELATORRE** [comment]
Closing this issue since it could not be reproed. File can be downloaded right.
Note that the URL from GitHub in order to download the plain data is this:

https://raw.githubusercontent.com/Azure/MachineLearningNotebooks/master/how-to-use-azureml/automated-machine-learning/forecasting-bike-share/bike-no.csv

Please, re-open if you continue having this issue.
