### ISSUE TITLE
AutoML and Mlflow

### ISSUE THREAD

**Issue by BlueMonday-Donovan-Wilson** [Azure/MachineLearningNotebooks#1411]
The integration between MLFlow and AzureML does not work effectively if running an AutoML experiment.
The only thing tracked on the parent and child runs is the metrics, however no parameters are tracked.
There is also no information in the tags about mlflow.
Without these parameters it is impossible to properly compare runs on the mlflow UI.

I ran a notebook with the following configuration steps for the workspace and mlflow

![image](https://user-images.githubusercontent.com/77375809/113050666-65e3ee80-91a5-11eb-9135-6c23ad585aff.png)

Then the following steps for the automl configuration.

![image](https://user-images.githubusercontent.com/77375809/113050865-a17eb880-91a5-11eb-8343-10b4206c8fee.png)

Then finally the following steps for the submitting the experiment. I have tried multiple variations of this step, this is just one of them.

![image](https://user-images.githubusercontent.com/77375809/113051091-e1de3680-91a5-11eb-914a-3e789cbd4fcf.png)

I am running this from the following conda environment.

name: azureml-env
dependencies:
    - python 3.6.13
    - pip=20.1
    - ipykernel
    - pip:
        - azureml-sdk[automl]
        - mlflow
        - azureml-mlflow
        - pandas==0.25.3
        - jinja2==2.11.2
        - flask==1.0.3
        - gunicorn==19.9.0
        - interpret-community==0.17.1
        - scikit-learn==0.22.2
        - scipy==1.5.2
        - interpret-core[required]==0.2.1
        - joblib==0.14.1
        - azure-core==1.11.0
        - azure-mgmt-resource==12.0.0
        - azure-common==1.1.26
        - cryptography==3.3.2
        - importlib-metadata==3.7.0
        - msal==1.9.0
        - protobuf==3.15.4
        - ruamel.yaml==0.16.12
        - s3transfer==0.3.4
        - tqdm==4.58.0
        - zipp==3.4.0
        - azure-cli-core
        - botocore==1.18.18
        - numpy==1.18.5

How do I get the automl run to track the parameters of the child runs so that it can be properly compared using the mflow UI?

**Comment by CESARDELATORRE** [comment]
Adding @SKrupa

**Comment by CESARDELATORRE** [comment]
@BlueMonday-Donovan-Wilson 
Just to let you know that "MLFlow+AutoML" is “in the works” but not ready yet.

MLFlow integration from AutoML for "Data Plane operations" is something we're actively investigating and starting to design for the next major version of the SDK (v2.0).  

It might be too soon for trying MLFlow+AutoML.
In any case, @SKrupa and Eduardo de Leon might provide some comments here.

**Comment by eedeleon** [comment]
@BlueMonday-Donovan-Wilson , this looks like an interesting use case. 

I would try to break down the issue to see if we can better understand why it is not working.

Autolog uses hooks in sklearn to find calls and log accordingly. I would expect the same behavior to happen with mlflow with "sqlite:///my.db". This narrows down the incompatibility to autolog and automl's use of sklearn internally.

In some cases, automl submits a remote job, this would not be compatible with autolog since the flag will not reach the remote machine.

If the automl job is local. It may be possible to debug why the calls to sklearn are not working, it is more than likely due to nesting of sklearn calls within a function. This nesting changes the scope for the sklearn calls. Monkeypatches, which is how autolog works, can be finnicky with nesting.

One way to get around this, to use the mlflow ui, is to find the info that you wish to log and use mlflow to log after the automl job. This may require use of the MlflowClient.

**Comment by CESARDELATORRE** [comment]
Closing this issue at the AML GitHub repo since this problem is related to MLFlow/OSS itself, so we encourage you to open an issue at Issues · mlflow/mlflow (github.com). You could use the example provided above by @eedeleon 
 
Please, feel free to re-open this issue if you think something else is related to Azure ML / AutoML in particular.
