### ISSUE TITLE
AutoML not working Python SDK

### ISSUE THREAD

**Issue by rahulnosedat** [Azure/MachineLearningNotebooks#1495]
I have previously also raised the issue that AutoML not working. 

![Screenshot 2021-06-01 140750](https://user-images.githubusercontent.com/82085316/120293902-5129f100-c2e3-11eb-8d93-34ba4a4d0308.png)

It says Current status: ModelSelection. Beginning model selection. After waiting for hours it doesn't proceed and gets stuck at Iteration 0.  Please solve this issue, it's been there for the last 3 months now. 

It works only when the dataset is very very small otherwise it stucks. Kindly look at this matter.

**Comment by CESARDELATORRE** [comment]
Hi @rahulnosedat,
In order for us to explore, can you provide the additional information about your experiment?
 
Size of Training Dataset:?:
Azure Region:
AutoML parent Run Id: 
Are you using local or remote (Azure compute) runs?:

Thank you,

**Comment by rahulnosedat** [comment]
Dear Cesar,

Thank you for your reply, I ran the same experiment a few months ago and there was no problem. 

**The shape of Train Data is:  (476627, 4) not much though
Azure Region: Europe - Germany
AutoML parent Run Id: AutoML_8d20a497-e10f-4d2f-a283-3cac5f4b992e
Running in the local environment.**

Thanking you, I hope the issue will be solved soon :) 

Best Regards
Rahul Bhat

**Comment by svaruag** [comment]
Hey @rahulnosedat - Thanks for sharing the information! It seems the first algorithm that was attempted in this case was "AutoArima", which is taking a long time to fit to the dataset. AutoArima trains a model per time series (grouped per your time series ID columns). As such, the training time scales linearly with the number of such groups, and if that's large in this dataset, we might need to be a little more patient. 

To verify that and unblock you, can you try to add "AutoArima" to the list of blocked models, and pass that in your AutoMLConfig? (e.g. `blocked_models=["AutoArima"])`
You can also verify it by sampling your dataset (so that it contains smaller number of series), and retrying.

Can you share if the last time you ran the same experiment, was the dataset size (and the configuration) the same as this time? And if AutoArima was attempted in that experiment?

**Comment by cartacioS** [comment]
Closing as the engineering team has provided additional information but received no reply. Please re-open if you are still facing the issue. Thanks!
