### ISSUE TITLE
Azure Machine Learning - Deploy of an AutoML Model trained in a Pipeline

### ISSUE THREAD

**Issue by LucaSavio** [Azure/MachineLearningNotebooks#1496]
Hello everyone,

I'm building a basic experiment for classifying customer service tickets based on different columns, so I've created a pipeline in three different steps:

 - preprocess data from a dataset
 - creates a model with AutoML
 - register and deploy it 
 
 The pipeline is required because I'd like to trigger it when new data are loaded in a datastore, that the dataset feeds from.

In the third step I'm able to register the best model from the AutoML step, but then the pipeline crashes when trying to get outputs from the best model (like the inference files that are automatically generated by AutoML, that I'd like to use for deployment): logs for the register_deploy step are quite clear,

**_Traceback (most recent call last):
  File "register_deploy.py", line 22, in <module>
    best_run, fitted_model = remote_run.get_output()
AttributeError: '_SubmittedRun' object has no attribute 'get_output'_**

I tried to do this in a simple AutoML experiment, and it works fine.
I couldn't find any example of AutoML + deploy pipelines (in every example I've found the model is only registered), so the code that I wrote for the pipeline is taken from different examples.
Can anyone help me?

As attachments, the register_deploy step script and the Python notebook that I'm using for creating the pipeline.

Thank you very much! 

[register_deploy.txt](https://github.com/Azure/MachineLearningNotebooks/files/6575471/register_deploy.txt)
[AutoML-Register-Deploy.txt](https://github.com/Azure/MachineLearningNotebooks/files/6575577/AutoML-Register-Deploy.txt)

**Comment by svaruag** [comment]
Hi @LucaSavio, thanks for the detailed description and attaching the scripts above!

The problem you're seeing above is that the call to `get_output()` is only available on [AutoMLRun](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.run.automlrun?view=azure-ml-py#get-output-iteration--typing-union-int--nonetype----none--metric--typing-union-str--nonetype----none--return-onnx-model--bool---false--return-split-onnx-model--typing-union-azureml-automl-core-onnx-convert-onnx-convert-constants-splitonnxmodelname--nonetype----none----kwargs--typing-any-----typing-tuple-azureml-core-run-run--typing-any-) and [AutoMLStepRun](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.automl_step.automlsteprun?view=azure-ml-py). When we do `Run.get_context()` within the training script (like in `register_deploy.py`), we get a generic [Run](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run.run?view=azure-ml-py#get-context-allow-offline-true--used-for-context-manager-false----kwargs-) object back, which doesn't have those special methods.

For this scenario, we want to be able to access the 'AutoMLStep' run that was used for the second step (i.e. '02_automl_module') _within_ the PythonScriptStep for deployment (i.e. '03_deploy'). To do that, we'll have to do the following:

1. Add `azureml-pipeline` as a dependency for your environment (that is passed to RunConfiguration and eventually to the '03_deploy' step)

2. Re-create the top-level pipeline run, and use it to get the AutoMLStepRun
```python
from azureml.pipeline.core import PipelineRun
from azureml.pipeline.steps.automl_step import AutoMLStepRun

remote_run = Run.get_contex()    # This is the current active run for '03_deploy'
pipeline_run_id = remote_run.parent().id
pipeline_run = PipelineRun(experiment=remote_run.experiment, run_id=pipeline_run_id )   # This is the Pipeline run, that orchestrates the overall pipeline
automl_step_run = AutoMLStepRun(pipeline_run.find_step_run("02_automl_module")[0])
```
The call to [find_step_run()](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.run.pipelinerun?view=azure-ml-py#find-step-run-name-) above helps us to get to the actual step run that was used by the preceding AutoML step.

3. Once you have the automl_step_run, you can call [get_best_child()](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-client/azureml.train.automl.run.automlrun?view=azure-ml-py#get-best-child-metric--typing-union-str--nonetype----none--onnx-compatible--bool---false----kwargs--typing-any-----azureml-core-run-run) to get the child run] with the best model.  Since the model is already available locally (and passed in as arguments to the script), I'd recommend to _not_ call `get_output()`, since that would try to un-pickle the model file in memory (and would thus require all the AutoML dependencies as well, which can make your environment quite heavy)
You can also pass in the name of the automl step as an argument to the script (register_deploy.py), and use that to create the automl_step_run above, instead of hardcoding it.

Please let us know if you run into any problems using the above steps.

**Comment by cartacioS** [comment]
Closing as the engineering team has provided additional information and a resolution. Please re-open if you are still facing this issue or need additional help. Thanks!
