### ISSUE TITLE
Delete Secrets from AML's Keyvault

### ISSUE THREAD

**Issue by MAQ-Ravijit-Ramana** [Azure/MachineLearningNotebooks#1525]
Recently we found out that our AML's Keyvault has 160 auto-created secrets. How can we manage/delete them ?

**Comment by MAQ-Ravijit-Ramana** [comment]
any replies ?

**Comment by denniseik** [comment]
Hi @MAQ-Ravijit-Ramana - Apologies for the delay in responding to you as this item got triaged in the team. Azure ML creates secrets in the Key Vault while managing connections to linked Azure services. As of today, there's no easy way to clean these up via the service. For manageability, we recommend creating a Key Vault instance per azure machine learning workspace. Could you maybe clarify your resource set up, and the management challenges created by this set up, so that we can plan for improving this experience?

**Comment by MAQ-Ravijit-Ramana** [comment]
@denniseik No worries, We had a check on number of secrets so we thought if we could reduce these rotate these secrets that would make it more secure.

**Comment by denniseik** [comment]
@MAQ-Ravijit-Ramana Thank you for the feedback, it will help us improve. With regards to key rotation, please also refer to this article: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-change-storage-access-key

**Comment by salilbapat** [comment]
We have fixed the code to delete the secrets when the service/endpoint is deleted
