### ISSUE TITLE
Error while adding environment variables to conda yml

### ISSUE THREAD

**Issue by kunalchamoli** [Azure/MachineLearningNotebooks#1649]
I am trying to make a environment in Azure Machine Learning using conda YML file from 
'''Environment.from_conda_specification'''
but I ran into this error while adding enviornment variable to the YML
```
UserErrorException: UserErrorException:
	Message: Environment error: unknown variables key in environment specification
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Environment error: unknown variables key in environment specification"
    }
}

```
but i have read it [here](https://stackoverflow.com/a/64625207) that enviornment variables are added to conda yml file using this syntax only.
I'm not getting error while running this on local, but this error is coming while on azure machine learning.

**Comment by vizhur** [comment]
The fix is coming with the next releases. To unblock yourself you can try
>>> from azureml.core.conda_dependencies import CondaDependencies
>>> CondaDependencies._VALID_YML_KEYS.append("variables")

Also, in a case you are looking for runtime variables set for the job the right place would be to set environment_variables under RunConfiguration
https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.runconfig.runconfiguration?view=azure-ml-py#variables

**Comment by vizhur** [comment]
feature is now available with the latest SDK
