### ISSUE TITLE
Force to stop an experiment?

### ISSUE THREAD

**Issue by windson87** [Azure/MachineLearningNotebooks#249]
Hey,
Is there a way to forcefully stop an experiment (like a dead loop one)?
Thanks!

**Comment by danielsc** [comment]
Through the SDK, you can call `run.cancel()`.
If you already closed the notebook that you started the run with, you can get it back with the following code snippet (`next()` will get you the next element in a generator, starting with the first, which is the last submitted run in the experiment)
```
from azureml.core import Workspace
ws = Workspace.from_config()
exp = ws.experiments['tf-mnist']
run = next(exp.get_runs())
run.cancel()
```
Or you can get the run by name:
```
from azureml.core import Workspace, Run
ws = Workspace.from_config()
exp = ws.experiments['tf-mnist']
run = Run(exp, 'tf-mnist_1560782640_921dbfa8')
run.cancel()
```
Also, the portal now has a cancel button (greyed out here, since the run is already completed):
![image](https://user-images.githubusercontent.com/8079390/60981815-e71d9280-a2eb-11e9-9e89-27745b21f24f.png)
