### ISSUE TITLE
download_file(*args, **kwargs) 

### ISSUE THREAD

**Issue by lovettchris** [Azure/MachineLearningNotebooks#253]
Why no documentation on download_file ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b5836ca-7af4-3070-3e68-3bf8a9728aae
* Version Independent ID: 4f8b1886-9f38-ff00-1e30-02476c707972
* Content: [azureml.core.run.Run class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run.run?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.run.Run.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.run.Run.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
Great question, @lovettchris. We'll look into it. I've opened a defect to track this. Thanks.

**Comment by eedeleon** [comment]
This issue is resolved. We clobbered our documentation with a decorator. Unfortunately, the documentation looked correct so it went unnoticed but the decorator had no documentation, hence the missing docs. @lovettchris @j-martens 

https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run.run?view=azure-ml-py
