### ISSUE TITLE
Blob/Gen2 support w/ service principal

### ISSUE THREAD

**Issue by DerekDDQP** [Azure/MachineLearningNotebooks#263]
Any plans to support ADLS Gen 2 storage accounts (using a service principal instead of an account or sas token)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abb6da6e-eb0a-616d-5c2f-3dd3bb659460
* Version Independent ID: 3196a898-00f8-bf48-e804-6249c2f3748d
* Content: [azureml.core.datastore.Datastore class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.datastore.datastore?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by jamescheng01** [comment]
Does anyone be able to use DataStore.register_azure_data_lake API to register Azure Data Lake Gen2 as a new data store for Azure ML service workspace?

**Comment by akshay-0** [comment]
We're currently working on adding support for ADLS gen2 storage accounts using service principals and expect it to be available in next SDK refresh.

Current api `DataStore.register_azure_data_lake` doesn't work for Gen2 accounts. We'll be introducing a new api `Datastore.register_azure_data_lake_gen2` specifically for ADLS gen 2 accounts.

**Comment by DerekDDQP** [comment]
Thanks that's great - how often is the SDK refreshed?

**Comment by j-martens** [comment]
It has been about every 2 weeks lately.

**Comment by blancNoir** [comment]
"Azure Data Lake Datastore supports data transfer and running U-Sql jobs using AML Pipelines.

It does not provide upload and download through the SDK."

Will upload and download from ADLS1/2 ever be supported for moving data from ADLS to an AmlCompute cluster for training or should I rely on keeping training data in blob storage for storage V1 in order to mount/move blob data to AmlCompute? How would this work with a V2 storage account associated with an AzureML Workspace since blob storage in that case is synonymous with blob and ADLS datastores cant use upload/download methods? Thanks.
