### ISSUE TITLE
How to regist local path to datastore

### ISSUE THREAD

**Issue by takashi-uesaka** [Azure/MachineLearningNotebooks#316]
I would like to test a script in local pc before running in compute cluster.
I saw sample scripts, path of data directory is a return value of Datasource.as_mount method.
How cloud I register local path to Datastore?

**Comment by cforbe** [comment]
Hi @takashi-uesaka instead of using a datastore, you can create a dataset from a local file and use that as a script paramaters. to access data. For more information on datasets, here is the documentation. https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-create-register-datasets 

We're currently in the process of updating our docs to feature datasets instead of datastores.
