### ISSUE TITLE
My experiment stuck in finalizing state

### ISSUE THREAD

**Issue by amardeepjaiman** [Azure/MachineLearningNotebooks#321]
Hi,
My experiment started and completed successfully. and got below logs :

The experiment completed successfully. Finalizing run...
Logging experiment finalizing status in history service
Cleaning up all outstanding Run operations, waiting 300.0 seconds
11 items cleaning up...
Cleanup took 3.240373134613037 seconds

But it gets stuck in Finalizing state which is visible in portal. Can somebody what kind of post processing is done in this state ?

**Comment by j-martens** [comment]
Thanks for your report. Are you still experiencing this issue? Thank you!

**Comment by joshbarth** [comment]
I was able to reproduce this issue. I had a separate thread running that was logging some performance data, but it never stopped (just an infinite loop in another thread, basically). Once my process finished nothing killed the thread and Azure happily waits for the thread to exit. Probably not a bug; I should have killed it before stopping.

**Comment by LalithShankar** [comment]
Hi, 
The issue being the pickled file gets created when train.py or train_log.py file is run independtly on local the .pkl file gets created.
Where as when it is run in the Azure ML studio the .pkl file gets created and gets deleted as soon as it gets created. I have ran the code to see if it gets created before deleting.
Maybe u help understand the issue.? and Can you give pointers on how the issue was resolved ?

![image](https://user-images.githubusercontent.com/26398485/223432521-6b2da4a4-443b-4aab-9bbf-0d328fdd3b3e.png)
