### ISSUE TITLE
cannot access this datasource "https://dprepdata.blob.core.windows.net/demo"

### ISSUE THREAD

**Issue by amberzh** [Azure/MachineLearningNotebooks#368]
When I access this datasource dataset_root = "https://dprepdata.blob.core.windows.net/demo", got "The specified resource does not exist. RequestId:21722555-801e-00bb-2842-0605fc000000 Time:2019-05-09T08:39:21.2973207Z"

**Comment by kenkadota** [comment]
@amberzh - Hello, could you give us some more repro steps ?

**Comment by cforbe** [comment]
Hi @amberzh Which notebook were you using this datasource?

**Comment by mlaskowski17** [comment]
same problem. It's tutorial: Regression part 2.

**Comment by j-martens** [comment]
@nibaccam can you replace? It is in https://review.docs.microsoft.com/en-us/azure/machine-learning/service/tutorial-data-prep?branch=master#load-data . and in https://github.com/Azure/MachineLearningNotebooks/blob/master/tutorials/regression-part1-data-prep.ipynb

**Comment by nibaccam** [comment]
Hi @amberzh,  based on the error described, are you trying to view the demo data by copying and pasting the link into a browser? or are you getting the error when you run that line of code from the tutorial notebook?

**Comment by MayMSFT** [comment]
Hi,
dataset_root = "https://dprepdata.blob.core.windows.net/demo" 
This is not a complete url for the blob. It refers to the demo folder in the blob, which means you will not be able to download/preview the data. In order to download/preview the data, you need a full url from blob and here is an example: 
https://dprepdata.blob.core.windows.net/demo/green-small/green_tripdata_2013-08.csv

What we are doing in the tutorial is to load all files inside the folder and aggregate the result into green_df_raw, and yellow_df_raw.

**Comment by j-martens** [comment]
Docs have been updated with this. Not the notebooks yet.

**Comment by nibaccam** [comment]
Thanks for your report. We've made the change in our docs and are updating the tutorial notebook. We shall now proceed to close this issue, #please-close. If you feel that your issue has not been resolved please reopen the issue and provide additional context.

**Comment by nibaccam** [comment]
#please-close

**Comment by amberz** [comment]
thanks for the help and guide, it's good to close it.

**Comment by nibaccam** [comment]
@amberz could you close this issue from your side please?

**Comment by amberzh** [comment]
Close the issue given the issue is solved.
