### ISSUE TITLE
Seems like this works ok with client id and client secret

### ISSUE THREAD

**Issue by kottofy** [Azure/MachineLearningNotebooks#416]
I generated the credentials with `az ad sp create-for-rbac --sdk-auth &gt; my.azureauth`. 

Can anyone confirm and maybe we could update the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31731eb3-e539-a563-6557-bb5c4d1e5fc8
* Version Independent ID: e773574b-f028-5293-0f12-84a6a0258b13
* Content: [azureml.core.authentication.ServicePrincipalAuthentication class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.authentication.serviceprincipalauthentication?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.authentication.ServicePrincipalAuthentication.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.authentication.ServicePrincipalAuthentication.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@aashishb, can you confirm?

**Comment by aashishb** [comment]
Can you follow up with Roope Astala?

**Comment by j-martens** [comment]
@rastala

**Comment by j-martens** [comment]
FYI - @Blackmist

**Comment by Blackmist** [comment]
Thanks for bringing this up @kottofy ! The `az ad sp` command should work fine for creating a service principal. I believe the full docs for using that command are at https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest. I'll work with the developers to get the notebook updated and/or create an equivalent page in the core docs.

Another thing (which I haven't tried yet, but should theoretically work,) is if you've installed the ML CLI extension, you can probably use `az ml workspace share` to grant the SP access to the workspace. Instead of through the portal. More info on that is at https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-manage-workspace-cli#share-a-workspace-with-another-user.

Thanks again for reporting!

**Comment by Blackmist** [comment]
Sorry for the late response on this @kottofy 
The information on authentication is now part of the https://docs.microsoft.com/en-us/azure/machine-learning/how-to-setup-authentication document.

#please-close

**Comment by vmagelo** [comment]
Added link in ServicePrincipalAuthentication SDK docs to article Blackmist indicates above.
