### ISSUE TITLE
How to register a model directly from pipeline?

### ISSUE THREAD

**Issue by Wellington-Noberto** [Azure/MachineLearningNotebooks#424]
I'm trying to create a pipeline that can build a model of machine learning. The following code is a part of the script of the estimator step. According to the tutorial from the documentation I should save the model in the directory named 'outputs'
 https://docs.microsoft.com/en-us/azure/machine-learning/service/tutorial-train-models-with-aml?view=azure-ml-py&toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpython%2Fapi%2Fazureml_py_toc%2Ftoc.json%3Fview%3Dazure-ml-py&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpython%2Fazureml_py_breadcrumb%2Ftoc.json%3Fview%3Dazure-ml-py

![1](https://user-images.githubusercontent.com/46430006/59288423-25bb2100-8c4a-11e9-9765-6b84c332126c.PNG)
And then try to register the model from this folder, but the file is not being saved in this directory.
![2](https://user-images.githubusercontent.com/46430006/59288429-294ea800-8c4a-11e9-8b62-351e19f0fed9.PNG)
![3](https://user-images.githubusercontent.com/46430006/59288435-2c499880-8c4a-11e9-83ab-77cec12bec42.PNG)
Despite that problem, what I really want is to register the model in the Workspace directly from the pipeline, instead of doing it from a local script, if possible.

**Comment by Wellington-Noberto** [comment]
It looks like I could register the model directly from the script that I am using in pipeline, but I stop in the same problem as before.
![out](https://user-images.githubusercontent.com/46430006/59533403-ba7b8400-8ec1-11e9-8310-4555ca5fb5df.PNG)
The 'outputs' folder is created as I thougth, but it seems that the folder isn't in the same directory as it was suppose to be. So I don't know how to manipulate the files inside this folder.
![6](https://user-images.githubusercontent.com/46430006/59533580-4a213280-8ec2-11e9-9559-a1bf496553ae.PNG)
'outputs' file should be in this directory

**Comment by girishnadiger-gep** [comment]
@Wellington-Noberto The issue is there are child run for each pipeline run, and the output folder will be present in the child runs which run individual steps in pipeline, not in the parent run which runs the pipeline. So if you extract child runs from pipeline_run then check in those child run objects with .get_file_names() method, you will be able to see your files.

Alternatively if you want to register your model, use the child run object, and not the parent run object.

**Comment by hillygoose** [comment]
I am having a very similar issue to this where the model I create from a pipeline step doesn't appear in the directory I assumed it would - just like this issue issue.

@Wellington-Noberto - did you manage to fix this and if so how?
@girishnadiger-gep  - can you share more info around extracting child runs from a pipeline run - from the docs I only see methods to create a child run rather than extracting any info from it
