### ISSUE TITLE
Azure SQL Database Error. Please check the correctness of the datastore information.

### ISSUE THREAD

**Issue by atimesastudios** [Azure/MachineLearningNotebooks#425]
Trying to register an Azure SQL Server database as a datastore in an Azure Machine Learning Workspace. Not sure if I have set up the Service Principal correctly. Is there a tutorial or blog post that explains the sequence of steps needed? Also is it possible to get finer level of error messages? There are 7 arguments for register_azure_sql_database but this 400 error is non-specific and not sure from the traceback where to start digging next.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abb6da6e-eb0a-616d-5c2f-3dd3bb659460
* Version Independent ID: 3196a898-00f8-bf48-e804-6249c2f3748d
* Content: [azureml.core.datastore.Datastore class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.datastore.datastore?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.datastore.Datastore.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@atimesastudios - Did you see this article? https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-access-data#training-compute-and-datastore-matrix

**Comment by Ultramann** [comment]
@j-martens The article you linked does not address this issue.

@atimesastudios I just got this working, I believe the issue you're running into is caused by your service principal not having access to the database. Here are the rough steps I followed (assuming you already have a service principal, secret, database, and workspace). For more detailed info about the first two steps look here: https://docs.microsoft.com/en-us/azure/sql-database/sql-database-aad-authentication-configure.

1. Login to the database as the active directory admin.
2. Add service principal as user to database:
`CREATE USER <Azure_AD_principal_name> FROM EXTERNAL PROVIDER;`
3. Grant the user privileges, I used `db_datareader`:
`ALTER ROLE [db_datareader] ADD MEMBER <Azure_AD_principal_name>;`
4. From the aml sdk in python, run `Datastore.register-azure-sql-database`. I don't remember seeing examples of this anywhere in the notebooks, I could be wrong about that though. Documentation can be found here:
https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.datastore.datastore?view=azure-ml-py#register-azure-sql-database-workspace--datastore-name--server-name--database-name--tenant-id--client-id--client-secret--resource-url-none--authority-url-none--endpoint-none--overwrite-false-.
