### ISSUE TITLE
deployment error on kubernetes - "code": "Unschedulable", "message": "0/3 nodes are available: 3 Insufficient nvidia.com/gpu."

### ISSUE THREAD

**Issue by amardeepjaiman** [Azure/MachineLearningNotebooks#487]
I am getting following error while deploying the model on Azure kubernetes Service.

Service deployment polling reached non-successful terminal state, current service state: Failed
Error:
{
  "code": "KubernetesError",
  "statusCode": 400,
  "message": "Kubernetes Deployment Error",
  "details": [
    {
      "code": "Unschedulable",
      "message": "0/3 nodes are available: 3 Insufficient nvidia.com/gpu."
    }
  ]
}

Service deployment polling reached non-successful terminal state, current service state: Failed
Error:
{
  "code": "KubernetesError",
  "statusCode": 400,
  "message": "Kubernetes Deployment Error",
  "details": [
    {
      "code": "Unschedulable",
      "message": "0/3 nodes are available: 3 Insufficient nvidia.com/gpu."
    }
  ]
}

---------------------------------------------------------------------------
WebserviceException                       Traceback (most recent call last)
~/anaconda3/envs/azureml/lib/python3.6/site-packages/azureml/core/webservice/webservice.py in wait_for_deployment(self, show_output)
    465                                           'Error:\n'
--> 466                                           '{}'.format(self.state, error_response), logger=module_logger)
    467             print('{} service creation operation finished, operation "{}"'.format(self._webservice_type,

WebserviceException: Service deployment polling reached non-successful terminal state, current service state: Failed
Error:
{
  "code": "KubernetesError",
  "statusCode": 400,
  "message": "Kubernetes Deployment Error",
  "details": [
    {
      "code": "Unschedulable",
      "message": "0/3 nodes are available: 3 Insufficient nvidia.com/gpu."
    }
  ]
}

During handling of the above exception, another exception occurred:

WebserviceException                       Traceback (most recent call last)
<ipython-input-42-50e14e209f39> in <module>
      2 
      3 service = Model.deploy(ws, "detect-face7", [detect_face_model], inference_config, aks_config, aks_target)
----> 4 service.wait_for_deployment(show_output = True)
      5 print(service.state)
      6 print(service.get_logs())

~/anaconda3/envs/azureml/lib/python3.6/site-packages/azureml/core/webservice/webservice.py in wait_for_deployment(self, show_output)
    473                                           'Current state is {}'.format(self.state), logger=module_logger)
    474             else:
--> 475                 raise WebserviceException(e.message, logger=module_logger)
    476 
    477     def _wait_for_operation_to_complete(self, show_output):

WebserviceException: Service deployment polling reached non-successful terminal state, current service state: Failed
Error:
{
  "code": "KubernetesError",
  "statusCode": 400,
  "message": "Kubernetes Deployment Error",
  "details": [
    {
      "code": "Unschedulable",
      "message": "0/3 nodes are available: 3 Insufficient nvidia.com/gpu."
    }
  ]
}

Whats the meaning of this error ?

Thanks,
Amardeep

**Comment by prwani** [comment]
+1. I am also facing same issue.

**Comment by kishan19** [comment]
+1. Am also facing the same.

**Comment by v-strudm-msft** [comment]
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. We will close it for now. Should you still need assistance with this or another issue, please re-post and we will respond promptly.

**Comment by Exlsunshine** [comment]
still seeing this error:
                                        More information can be found using '.get_logs()'
E                                                     Error:
E                                                     {
E                                                       "code": "KubernetesError",
E                                                       "statusCode": 400,
E                                                       "message": "Kubernetes Deployment Error",
E                                                       "details": [
E                                                         {
E                                                           "code": "Unschedulable",
E                                                           "message": "0/6 nodes are available: 6 Insufficient nvidia.com/gpu."
E                                                         },
E                                                         {
E                                                           "code": "DeploymentFailed",
E                                                           "message": "Couldn't Schedule because the kubernetes cluster didn't have available resources after trying for 00:05:00."
E                                                         }
E                                                       ]
E                                                     }
E                                                     	InnerException None

**Comment by csteegz** [comment]
The error message literally indicates the issue, none of the nodes have GPUs available. 
Please take a look at the skus that [include GPUs](https://docs.microsoft.com/en-us/azure/aks/gpu-cluster) or use an environment that does not require a GPU.

**Comment by gvashishtha** [comment]
Thanks, Colin, for your help! @all on this thread, seems like you are being guided to use GPU's but may not actually need them. If you can share the link to the tutorial/documentation you were following, would be helpful to understand why you are trying to use GPU's.
