### ISSUE TITLE
Date Field missing

### ISSUE THREAD

**Issue by motorreiziger** [Azure/MachineLearningNotebooks#552]
Hi! I Tried to load the GFS Dataset and missing a datetime, the only date field is currentDatetime. Is that the date of the NOAA forecastfile or the forecast date itself? If so, the most recent data is a few days behind.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ceb9bc-fcf6-dc48-ab4c-52ff75eb2783
* Version Independent ID: 77bc3ca6-589f-15fc-fbd0-33d39475c9b3
* Content: [azureml.opendatasets package - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-opendatasets/azureml.opendatasets?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-opendatasets/azureml.opendatasets.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-opendatasets/azureml.opendatasets.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YoYoJa** [comment]
@motorreiziger  The currentDatetime means the forecast model cycle runtime, together with it , there is a column forecastHour means the hour since currentDatetime. Basically GFS contains forecasted weather data regularly, and each time (column “currentDatetime”) it will forecast multiple hours ahead (forecastHour), from hours up to several days, usually the next 15 days. Combine those 2 columns then you can get the exact forecasting time.

**Comment by PeterCLu** [comment]
@motorreiziger Thanks for your report. Since we haven't heard back from you in awhile, we will be closing this issue. If you feel that your issue hasn't been resolved please re-open a new issue.
