### ISSUE TITLE
Datastore.download() expecting a parent directory as prefix

### ISSUE THREAD

**Issue by jadhosn** [Azure/MachineLearningNotebooks#689]
I'm trying to download a sub-directory from a file share I have registered in my workspace. It seems the `Datastore.download()` method only allows a parent directory to be a prefix. 
For example, in this sample structure below, I am only able to download the parent directory `parent_dir` but I can't specify `./parent_dir/dir1`

>./parent_dir
./parent_dir/dir1
./parent_dir/dir1/file1.py
./parent_dir/dir2
etc.
```python 
from azureml.core.datastore import Datastore

my_ds = Datastore.get(ws, "jad")

# Line below downloads the whole parent directory
my_ds.download(target_path="./output", prefix="parent_dir", overwrite=False) 

# Line below doesn't download anything
my_ds.download(target_path="./output", prefix="parent_dir/dir1", overwrite=False) 
```

**Comment by YutongTie-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by MayMSFT** [comment]
Hi! I just tried download a sub-directory from datastore and it works fine. 
a few possible steps for you to try & debug:
1. update the azureml-sdk to the latest version by running "pip -U azureml-sdk"
2. try download the subdirectory into a different folder. e.g. output2. because u downloaded the full parent directory in the first line, when u run the second line to download a sub-directory, the file paths already exists, so we will skip the download.

**Comment by nicolemhfarley** [comment]
I would like to be able to download individual files from a directory but am only able to download everything within a given directory.  This happens even if I only specify a single file.  Is there a way to be more selective?
