### ISSUE TITLE
unpickle error

### ISSUE THREAD

**Issue by annaymj** [Azure/MachineLearningNotebooks#699]
Got this error when trying to build a binary classification model, can anyone please help?
'''

****************************************************************************************************
		ITERATION: The iteration being evaluated.
		PIPELINE: A summary description of the pipeline being evaluated.
		DURATION: Time taken for the current iteration.
		METRIC: The result of computing score on the fitted pipeline.
		BEST: The best observed score thus far.
		****************************************************************************************************
		
		 ITERATION   PIPELINE                                       DURATION      METRIC      BEST
		         0                                                  0:06:48          nan       nan
		ERROR: Run AutoML_b2ad2b97-ab48-4672-a7f7-e745adb7494b_0 failed with exception "AutoMLPickleException:
		  Message: UnPickle error 
		  InnerException None
		  ErrorResponse 
		{
		    "error": {
		        "code": "System",
		        "message": "UnPickle error "
		    }
		}".
		         1                                                  0:00:28          nan       nan
		ERROR: Run AutoML_b2ad2b97-ab48-4672-a7f7-e745adb7494b_1 failed with exception "AutoMLPickleException:
		  Message: UnPickle error 
		  InnerException None
		  ErrorResponse 
		{
		    "error": {
		        "code": "System",
		        "message": "UnPickle error "
		    }
		}".
         2 
'''

**Comment by YutongTie-MSFT** [comment]
@annaymj 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by annaymj** [comment]
Any update? Happy New Year!

**Comment by CESARDELATORRE** [comment]
#please-close This issue is probably stale.
@annaymj We're sorry that this issue got lost. 
Please, re-open this issue if you'd like us to research the issue.
However, I think that in that case you should try with the latest AutoML versions since if this issue was a bug, it might have been solved after quite a few newer versions released after this happened. 

If you re-open, please provide:
- Azure ML SDK version used
- Notebook with source code to reproduce it
- Sample dataset to use it with that notebook
- Run ID of the run where it happens
- Log files related to that run
