### ISSUE TITLE
Azure ML Studio - Cannot Create Data Labelling Projects - Hangs on "Initializing"

### ISSUE THREAD

**Issue by iannovic** [Azure/MachineLearningNotebooks#730]
In Azure Machine Learning Studio, I am trying to create a new Object Detection (Bounding Box) Data Labelling Project.  The projects seem to hang on initialization no matter which dataset the project is using.

There are six projects total, spanning two different azure ml workspaces, each using a different dataset. The datasets have either JPG, BMP, or PNG file formats. 

**Datasets used by different label projects (in order)**
1. Dataset1: 80 .bmp image files with additional jsons
2. Dataset2: 80 .bmp image files, only
3. Dataset3: 80 .png files, only
4. Dataset4: 3 .png files, only
5. Dataset5: 3 .jpg files, only

I created each of these data sets, then created a new labelling project with the exact same configurations for each of these different datasets.

**Workspace 1 labelling projects**
![image](https://user-images.githubusercontent.com/6504498/72184156-c24ec880-33bd-11ea-9f3d-7f7e6b470437.png)

I then even created a new machine learning service workspace and used Dataset5 to create a sixth labelling project. the error seems to persist in a different, completely vanilla workspace.

**Workspace 2 labelling projects**
![image](https://user-images.githubusercontent.com/6504498/72184337-38ebc600-33be-11ea-8116-faaa0906111f.png)

**Comment by iannovic** [comment]
four hours later, the labelling projects finished initializing. I was just being impatient :)

**Comment by iannovic** [comment]
Reopening this. I keep experiencing long project initializing times for labelling projects. What is a "reasonable" initialization time for a labelling project? I have been on average waiting three hours to create new projects, with reasonably sized datasets (100 or less images)

Please let me know if you need more information!

**Comment by YutongTie-MSFT** [comment]
@iannovic 

Thanks for reaching out to us. Since this repo is for Machine Learning Notebook only, please open a new forum thread in [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=AzureMachineLearningService) as it could be better place to get help on your scenario. These forum community members could provide their expert guidance on your scenario based on their experience. Thanks.

We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
