### ISSUE TITLE
y values are present for each date. Nothing to forecast. while inferencing Orange juice forecast automl model on ACI

### ISSUE THREAD

**Issue by guybartal** [Azure/MachineLearningNotebooks#790]
I've tried to train latest (v1.0.83) Orange juice forecast model on AutoML, and got exception on inferencing with ACI:

```
import json
X_query = X_test.copy()
# We have to convert datetime to string, because Timestamps cannot be serialized to JSON.
X_query[time_column_name] = X_query[time_column_name].astype(str)

# The Service object accept the complex dictionary, which is internally converted to JSON string.
# The section 'data' contains the data frame in the form of dictionary.
test_sample = json.dumps({'data': X_query.to_dict(orient='records')})
response = aci_service.run(input_data = test_sample)
# translate from networkese to datascientese
try: 
    res_dict = json.loads(response)
    y_fcst_all = pd.DataFrame(res_dict['index'])
    y_fcst_all[time_column_name] = pd.to_datetime(y_fcst_all[time_column_name], unit = 'ms')
    y_fcst_all['forecast'] = res_dict['forecast']    
except:
    print(res_dict)
```

> {'error': 'DataException:\n\tMessage: y values are present for each date. Nothing to forecast.\n\tInnerException None\n\tErrorResponse \n{\n    "error": {\n        "code": "UserError",\n        "inner_error": {\n            "code": "InvalidData"\n        },\n        "message": "y values are present for each date. Nothing to forecast."\n    }\n}'}

**Comment by cartacioS** [comment]
Hello,

Seems the code above is missing the line of code that fills y_query with nan values (basically hiding the results from the model so that it can predict these). Try the code block below instead.

`import json
# The request data frame needs to have y_query column which corresponds to query.
X_query = X_test.copy()
X_query['y_query'] = np.NaN
# We have to convert datetime to string, because Timestamps cannot be serialized to JSON.
X_query[time_column_name] = X_query[time_column_name].astype(str)
# The Service object accept the complex dictionary, which is internally converted to JSON string.
# The section 'data' contains the data frame in the form of dictionary.
test_sample = json.dumps({'data': X_query.to_dict(orient='records')})
response = aci_service.run(input_data = test_sample)
# translate from networkese to datascientese
try: 
    res_dict = json.loads(response)
    y_fcst_all = pd.DataFrame(res_dict['index'])
    y_fcst_all[time_column_name] = pd.to_datetime(y_fcst_all[time_column_name], unit = 'ms')
    y_fcst_all['forecast'] = res_dict['forecast']    
except:
    print(res_dict)`

I was able to successfully run this using the script above and latest (v 1.0.85).

Thanks,
Sabina

**Comment by GiftA-MSFT** [comment]
@guybartal please let us know if the above suggestion resolved your issue. Thanks.
