### ISSUE TITLE
PipelineData "name" parameter is required when it should not be

### ISSUE THREAD

**Issue by stemoor** [Azure/MachineLearningNotebooks#838]
Hi, 

I have noted that when passing name=None in the PipelineData constructor, and passing a output_name instead, it throws an error:

```python
ValueError: PipelineData name cannot be empty
```
 However, as per described in the documentation below, this should not be the case:
```
output_name
str
The name of the output, if None name is used. Can contain only letters, digits, and underscores.
```

**Comment by swanderz** [comment]
@stemoor yeah kind of confusing bc there's two name-related parameters to [`PipelineData`](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipelinedata?view=azure-ml-py):
- `name`, and
- `output_name`
`name` is required. `output_name` is only required if you need to save it to a particular path instead of a path that's auto-created using the `name` param. @MayMSFT

**Comment by shbijlan** [comment]
#please-close
