### ISSUE TITLE
'_SubmittedRun' object has no attribute 'run_id'

### ISSUE THREAD

**Issue by dumbledad** [Azure/MachineLearningNotebooks#865]
```
run = Run.get_context()
run_id = run.run_id
```

Produces the error

>  AttributeError: '_SubmittedRun' object has no attribute 'run_id'

Surely this is how [the documentation](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run(class)?view=azure-ml-py) describes getting the run_id programatically?

**Comment by akshaya-a** [comment]
I think we have a bug in our documentation so it's a bit confusing. This section should render the actual property names but doesn't appear to be doing so: https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run(class)?view=azure-ml-py#attributes

I believe you want run.id instead of run.run_id

**Comment by j-martens** [comment]
@akshaya-a - is there a doc bug somewhere to track this?

**Comment by gilahenry** [comment]
In our case, we used the parent's id (the submitted pipeline current run id instead of the step id) :
```
from azureml.core import Run
run = Run.get_context()
run.parent.id
```
